
all: motor-dshot


motor-dshot: motor-dshot.c ../motor-common.c ../motor-common.h 
	gcc -O2 -S -o motor-dshot.s motor-dshot.c 
	gcc -g -O2 -Wall -o motor-dshot ../motor-common.c motor-dshot.c -lm

test2: always
	gcc -O2 -Wall -o test2 test2.c motor-dshot.c

clean: always
	rm -f *~ motor-dshot test test2 motor-dshot.s

.PHONY: always



